chore(clients): remove unnecessary copy to help debug build fails

diff --git a/clients/reth/Dockerfile.git b/clients/reth/Dockerfile.git
--- a/clients/reth/Dockerfile.git
+++ b/clients/reth/Dockerfile.git
@@ -8,22 +8,19 @@ ARG github=paradigmxyz/reth
 ARG tag=main
 
 # Update system and install necessary dependencies
-RUN apt-get update && apt-get install -y libclang-dev pkg-config build-essential \
-    && echo "Cloning: $github - $tag" \
+RUN apt-get update && apt-get install -y libclang-dev pkg-config build-essential
+
+RUN echo "Cloning: $github - $tag" \
     && git clone --depth 1 --branch $tag https://github.com/$github reth \
     && cd reth \
-    && cargo build --release \
-    && ls -lh target/release \
-    && cp target/release/reth /usr/local/bin/reth \
-    || { echo "Cargo build or copy failed"; exit 1; }
+    && cargo build --release || { echo "cargo build failed"; exit 1; }
 
 ## Final stage: Sets up the environment for running reth
 FROM debian:latest
 RUN apt-get update && apt-get install -y bash curl jq \
     && apt-get clean && rm -rf /var/lib/apt/lists/*
 
-# Copy compiled binary from builder
-COPY --from=builder /usr/local/bin/reth /usr/local/bin/reth
+COPY --from=builder /reth/target/release/reth /usr/local/bin/reth
 
 # Add genesis mapper script, startup script, and enode URL retriever script
 COPY genesis.json /genesis.json
